name: foundcalc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  window_size: ^0.1.0
  flutter:
    sdk: flutter
  excel: ^4.0.6
  file_picker: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/generalShear.xlsx
    - assets/localShear.xlsx
    - assets/images/combinedFooting.png
    - assets/images/retModel1-1.png
    - assets/images/retModel2-1.png
    - assets/images/retModel3-1.png
    - assets/images/retModel4-1.png
    - assets/images/retModel5-1.png
    - assets/images/retModel6-1.png
    - assets/images/retModel7-1.png
    - assets/images/retModel8-1.png
