name: foundcalc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  window_size: ^0.1.0
  flutter:
    sdk: flutter
  excel: ^4.0.6
  file_picker: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/generalShear.xlsx
    - assets/localShear.xlsx
    - assets/images/combinedFooting.png
    - assets/images/combined.png
    - assets/images/combined/reinforcementLeft.png
    - assets/images/combined/reinforcementRight.png
    - assets/images/retWall1-1.png
    - assets/images/retWall2-1.png
    - assets/images/retWall3-1.png
    - assets/images/retWall4-1.png
    - assets/images/retWall5-1.png
    - assets/images/retWall6-1.png
    - assets/images/retWall7-1.png
    - assets/images/retWall8-1.png
    - assets/images/rectMomentLoading/rectMoment1-1.png
    - assets/images/rectMomentLoading/rectMoment2-1.png
    - assets/images/rectMomentLoading/rectMoment3-1.png
    - assets/images/rectMomentLoading/rectMoment4-1.png
    - assets/images/rectMomentLoading/rectMoment5-1.png
    - assets/images/rectMomentLoading/rectMoment6-1.png
    - assets/images/rectMomentLoading/rectMoment7-1.png
    - assets/images/rectMomentLoading/rectMoment8-1.png
    - assets/images/rectMomentLoading/rectMoment9-1.png
    - assets/images/rectMomentLoading/rectMoment10-1.png
    - assets/images/rectMomentTopView/rectTopView1-1.png
    - assets/images/rectMomentTopView/rectTopView2-1.png
    - assets/images/rectMomentTopView/rectTopView3-1.png
    - assets/images/rectMomentTopView/rectTopView4-1.png
    - assets/images/design/design1.png
    - assets/images/design/design2.png
    - assets/images/design/design3.png
    - assets/images/deep/groupCircle.png
    - assets/images/deep/groupSquare.png
    - assets/images/deep/indivCircle.png
    - assets/images/deep/indivSquare.png
